# -*- coding: utf-8 -*-
"""helper_functions__OOP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zswd9JxGqRBkXnQUgHK1XyfxKUybCRF8
"""

import pandas as pd
from pandas import DataFrame

class OutlierRemover(pd.DataFrame):

    def __init__(self, file):
      super().__init__(pd.read_csv(file))

  """ This function calculates and removes outliers using the 1.5*IQR formula"""
    
   
    Q1 = dataframe.quantile(q=.25)
    Q3 = dataframe.quantile(q=.75)
    IQR = dataframe.apply(stats.iqr)
    outlier_remover = data[~((data < (Q1-1.5*IQR)) | (data > (Q3+1.5*IQR))).any(axis=1)]

class Customframe(DataFrame):
  """ This function adds a column of corresponding state names.

  Params (my_df) a DataFrame with a column called "abbrev" that has state abbreviations
  """

def add_state_names_column(self):
  """adding column of corresponding state names"""
  

  names_map = {"CA": "Cali", "CO": "Colo", "CT": "Conn"}
  self["name"] = self['abbrev'].map(names_map)

if __name__ == "__main__":

  custom_frame = custom_frame({"abbrev": ["CA", "CO", "CT"]})
  print(custom_frame.head())

  custom_frame.add_state_names_column()
  print(custom_frame.head())

class null_count(self):
    def __init__(self, file):
      super().__init__(pd.read_csv(file))

  """ This function caluclates the number of null values in a dataframe and returns 
  the results"""
  
  return self.isnull().sum().sum()
  print("The number of missing values of the dataframe is",null_count)